#!/bin/bash
rm -fR net-parscp/ && \
tar xvzf net-parscp.tgz && \
cd net-parscp &&\
export DEVELOPER=casiano &&\
export TESTMACHINES=bo &&\
perl Makefile.PL &&\
make veryclean &&\
perl Makefile.PL &&\ 
make &&\
make test TEST_VERBOSE=1

